### PR TITLE
Add mac

### PR DESCRIPTION
**Pull request by gustavscholin**

### CODE REVIEW

**Comment by aleda145** [comment]
Working late :sleepy: :smile: ?

**Comment by aleda145** [comment]
Could be really cool to automatically detect which OS/package manager install packages for. The git username/email could also be set from the startup script I suppose, if we want to make it user and platform independent!

**Comment by gustavscholin** [comment]
> Working late 😪 😄 ?

Haha yeah, sry for the accidental PR, targeted your main branch instead of my own 😅

**Comment by aleda145** [comment]
No worries!!

**Comment by gustavscholin** [comment]
> Could be really cool to automatically detect which OS/package manager install packages for. The git username/email could also be set from the startup script I suppose, if we want to make it user and platform independent!

Yeah that would be nice, I'm guessing it would be quite easy to just using the `uname`-command

**Pull request closed without merging**
